import { edgeCorners } from './cornerTable.js';

// Each rotation is a length-8 array: rotation[oldCorner] = newCorner
// Generated by composing face-up selections with Z-axis spins.
// Corner index = x + y*2 + z*4, so (x,y,z) <-> (i&1, (i>>1)&1, (i>>2)&1)

function makeCornerPerm(xform) {
  const perm = new Array(8);
  for (let i = 0; i < 8; i++) {
    const x = i & 1, y = (i >> 1) & 1, z = (i >> 2) & 1;
    const [nx, ny, nz] = xform(x, y, z);
    perm[i] = nx + ny * 2 + nz * 4;
  }
  return perm;
}

// Compose two corner permutations: apply a then b
function compose(a, b) {
  return a.map(c => b[c]);
}

// Primitive rotations (right-hand rule, acting on corner coordinates)
const RZ = makeCornerPerm((x, y, z) => [1 - y, x, z]);       // 90° around +Z
const RX = makeCornerPerm((x, y, z) => [x, 1 - z, y]);       // 90° around +X
const RY = makeCornerPerm((x, y, z) => [z, y, 1 - x]);       // 90° around +Y

function applyN(perm, n) {
  let r = [0, 1, 2, 3, 4, 5, 6, 7]; // identity
  for (let i = 0; i < n; i++) r = compose(r, perm);
  return r;
}

// Generate all 24 orientations: 6 faces up × 4 Z-spins
const faceUps = [
  applyN(RX, 0), // +Z up (identity)
  applyN(RX, 1), // +Y up
  applyN(RX, 2), // -Z up
  applyN(RX, 3), // -Y up
  compose(applyN(RY, 1), applyN(RX, 0)), // +X up
  compose(applyN(RY, 3), applyN(RX, 0)), // -X up
];

export const rotations = [];
for (const face of faceUps) {
  for (let spin = 0; spin < 4; spin++) {
    rotations.push(compose(face, applyN(RZ, spin)));
  }
}

// Remove duplicates (some face+spin combos are identical)
const seen = new Set();
const uniqueRotations = [];
for (const r of rotations) {
  const key = r.join(',');
  if (!seen.has(key)) {
    seen.add(key);
    uniqueRotations.push(r);
  }
}
// Should be exactly 24
if (uniqueRotations.length !== 24) {
  throw new Error(`Expected 24 rotations, got ${uniqueRotations.length}`);
}

export { uniqueRotations as rotations24 };

export function rotateCornerMask(rotation, mask) {
  let newMask = 0;
  for (let c = 0; c < 8; c++) {
    if (mask & (1 << c)) newMask |= 1 << rotation[c];
  }
  return newMask;
}

export function rotateEdge(rotation, edgeIndex) {
  const [a, b] = edgeCorners[edgeIndex];
  const ra = rotation[a], rb = rotation[b];
  // Find the edge matching (ra, rb) or (rb, ra)
  for (let e = 0; e < 12; e++) {
    const [ea, eb] = edgeCorners[e];
    if ((ea === ra && eb === rb) || (ea === rb && eb === ra)) return e;
  }
  throw new Error(`No edge found for rotated corners ${ra},${rb}`);
}
